# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aerolinea.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_formMainWindow(object):
    def setupUi(self, formMainWindow):
        formMainWindow.setObjectName(_fromUtf8("formMainWindow"))
        formMainWindow.resize(602, 376)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bookman Old Style"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        formMainWindow.setFont(font)
        formMainWindow.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.widget = QtGui.QWidget(formMainWindow)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridTabWidget = QtGui.QTabWidget(self.widget)
        self.gridTabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bookman Old Style"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.gridTabWidget.setFont(font)
        self.gridTabWidget.setAccessibleName(_fromUtf8(""))
        self.gridTabWidget.setObjectName(_fromUtf8("gridTabWidget"))
        self.agregar = QtGui.QWidget()
        self.agregar.setObjectName(_fromUtf8("agregar"))
        self.gridLayout_6 = QtGui.QGridLayout(self.agregar)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_9 = QtGui.QLabel(self.agregar)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.nodoLineEdit = QtGui.QLineEdit(self.agregar)
        self.nodoLineEdit.setObjectName(_fromUtf8("nodoLineEdit"))
        self.gridLayout_6.addWidget(self.nodoLineEdit, 1, 0, 1, 1)
        self.agregarPushButton = QtGui.QPushButton(self.agregar)
        self.agregarPushButton.setObjectName(_fromUtf8("agregarPushButton"))
        self.gridLayout_6.addWidget(self.agregarPushButton, 2, 0, 1, 1)
        self.gridTabWidget.addTab(self.agregar, _fromUtf8(""))
        self.conectar = QtGui.QWidget()
        self.conectar.setObjectName(_fromUtf8("conectar"))
        self.gridLayout = QtGui.QGridLayout(self.conectar)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.destino = QtGui.QLabel(self.conectar)
        self.destino.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.destino.setObjectName(_fromUtf8("destino"))
        self.gridLayout.addWidget(self.destino, 1, 0, 1, 1)
        self.destinoLineEdit = QtGui.QLineEdit(self.conectar)
        self.destinoLineEdit.setObjectName(_fromUtf8("destinoLineEdit"))
        self.gridLayout.addWidget(self.destinoLineEdit, 1, 1, 1, 1)
        self.origen = QtGui.QLabel(self.conectar)
        self.origen.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.origen.setObjectName(_fromUtf8("origen"))
        self.gridLayout.addWidget(self.origen, 0, 0, 1, 1)
        self.origenLineEdit = QtGui.QLineEdit(self.conectar)
        self.origenLineEdit.setObjectName(_fromUtf8("origenLineEdit"))
        self.gridLayout.addWidget(self.origenLineEdit, 0, 1, 1, 1)
        self.distanciaLineEdit = QtGui.QLineEdit(self.conectar)
        self.distanciaLineEdit.setObjectName(_fromUtf8("distanciaLineEdit"))
        self.gridLayout.addWidget(self.distanciaLineEdit, 2, 1, 1, 1)
        self.fechaArribo = QtGui.QLabel(self.conectar)
        self.fechaArribo.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.fechaArribo.setObjectName(_fromUtf8("fechaArribo"))
        self.gridLayout.addWidget(self.fechaArribo, 4, 0, 1, 1)
        self.distancia = QtGui.QLabel(self.conectar)
        self.distancia.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.distancia.setObjectName(_fromUtf8("distancia"))
        self.gridLayout.addWidget(self.distancia, 2, 0, 1, 1)
        self.salidaDateEdit = QtGui.QDateEdit(self.conectar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bookman Old Style"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.salidaDateEdit.setFont(font)
        self.salidaDateEdit.setObjectName(_fromUtf8("salidaDateEdit"))
        self.gridLayout.addWidget(self.salidaDateEdit, 3, 1, 1, 1)
        self.fechaSalida = QtGui.QLabel(self.conectar)
        self.fechaSalida.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.fechaSalida.setObjectName(_fromUtf8("fechaSalida"))
        self.gridLayout.addWidget(self.fechaSalida, 3, 0, 1, 1)
        self.arriboDateEdit = QtGui.QDateEdit(self.conectar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bookman Old Style"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.arriboDateEdit.setFont(font)
        self.arriboDateEdit.setObjectName(_fromUtf8("arriboDateEdit"))
        self.gridLayout.addWidget(self.arriboDateEdit, 4, 1, 1, 1)
        self.registrarPushButton = QtGui.QPushButton(self.conectar)
        self.registrarPushButton.setEnabled(True)
        self.registrarPushButton.setObjectName(_fromUtf8("registrarPushButton"))
        self.gridLayout.addWidget(self.registrarPushButton, 5, 1, 1, 1)
        self.gridTabWidget.addTab(self.conectar, _fromUtf8(""))
        self.mostrar = QtGui.QWidget()
        self.mostrar.setObjectName(_fromUtf8("mostrar"))
        self.gridLayout_3 = QtGui.QGridLayout(self.mostrar)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.mostrarPushButton = QtGui.QPushButton(self.mostrar)
        self.mostrarPushButton.setEnabled(True)
        self.mostrarPushButton.setObjectName(_fromUtf8("mostrarPushButton"))
        self.gridLayout_3.addWidget(self.mostrarPushButton, 1, 0, 1, 1)
        self.mostrarTableWidget = QtGui.QTableWidget(self.mostrar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bookman Old Style"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.mostrarTableWidget.setFont(font)
        self.mostrarTableWidget.setAutoFillBackground(False)
        self.mostrarTableWidget.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";\n"
""))
        self.mostrarTableWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mostrarTableWidget.setLineWidth(1)
        self.mostrarTableWidget.setMidLineWidth(0)
        self.mostrarTableWidget.setRowCount(0)
        self.mostrarTableWidget.setColumnCount(5)
        self.mostrarTableWidget.setObjectName(_fromUtf8("mostrarTableWidget"))
        item = QtGui.QTableWidgetItem()
        self.mostrarTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mostrarTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mostrarTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.mostrarTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.mostrarTableWidget.setHorizontalHeaderItem(4, item)
        self.mostrarTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.mostrarTableWidget.horizontalHeader().setDefaultSectionSize(113)
        self.gridLayout_3.addWidget(self.mostrarTableWidget, 0, 0, 1, 1)
        self.gridTabWidget.addTab(self.mostrar, _fromUtf8(""))
        self.modificar = QtGui.QWidget()
        self.modificar.setObjectName(_fromUtf8("modificar"))
        self.gridLayout_4 = QtGui.QGridLayout(self.modificar)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.buscarPushButton = QtGui.QPushButton(self.modificar)
        self.buscarPushButton.setObjectName(_fromUtf8("buscarPushButton"))
        self.gridLayout_4.addWidget(self.buscarPushButton, 0, 0, 1, 1)
        self.buscarLineEdit = QtGui.QLineEdit(self.modificar)
        self.buscarLineEdit.setObjectName(_fromUtf8("buscarLineEdit"))
        self.gridLayout_4.addWidget(self.buscarLineEdit, 0, 1, 1, 2)
        self.modificarTableWidget = QtGui.QTableWidget(self.modificar)
        self.modificarTableWidget.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.modificarTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.modificarTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.modificarTableWidget.setRowCount(0)
        self.modificarTableWidget.setColumnCount(5)
        self.modificarTableWidget.setObjectName(_fromUtf8("modificarTableWidget"))
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.modificarTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.modificarTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.modificarTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.modificarTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.modificarTableWidget.setHorizontalHeaderItem(4, item)
        self.modificarTableWidget.horizontalHeader().setDefaultSectionSize(113)
        self.gridLayout_4.addWidget(self.modificarTableWidget, 1, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.modificar)
        self.label_3.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.modificar)
        self.label_4.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.modificar)
        self.label_5.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.modificar)
        self.label.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 5, 0, 1, 1)
        self.modSalidaDateEdit = QtGui.QDateEdit(self.modificar)
        self.modSalidaDateEdit.setObjectName(_fromUtf8("modSalidaDateEdit"))
        self.gridLayout_4.addWidget(self.modSalidaDateEdit, 5, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.modificar)
        self.label_6.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 5, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.modificar)
        self.label_2.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 6, 0, 1, 1)
        self.modArriboDateEdit = QtGui.QDateEdit(self.modificar)
        self.modArriboDateEdit.setObjectName(_fromUtf8("modArriboDateEdit"))
        self.gridLayout_4.addWidget(self.modArriboDateEdit, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.modificar)
        self.label_7.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 6, 2, 1, 1)
        self.modificarPushButton = QtGui.QPushButton(self.modificar)
        self.modificarPushButton.setObjectName(_fromUtf8("modificarPushButton"))
        self.gridLayout_4.addWidget(self.modificarPushButton, 7, 1, 1, 1)
        self.modDistanciaLineEdit = QtGui.QLineEdit(self.modificar)
        self.modDistanciaLineEdit.setObjectName(_fromUtf8("modDistanciaLineEdit"))
        self.gridLayout_4.addWidget(self.modDistanciaLineEdit, 4, 1, 1, 2)
        self.modDestinoLineEdit = QtGui.QLineEdit(self.modificar)
        self.modDestinoLineEdit.setObjectName(_fromUtf8("modDestinoLineEdit"))
        self.gridLayout_4.addWidget(self.modDestinoLineEdit, 3, 1, 1, 2)
        self.modOrigenLineEdit = QtGui.QLineEdit(self.modificar)
        self.modOrigenLineEdit.setObjectName(_fromUtf8("modOrigenLineEdit"))
        self.gridLayout_4.addWidget(self.modOrigenLineEdit, 2, 1, 1, 2)
        self.gridTabWidget.addTab(self.modificar, _fromUtf8(""))
        self.ordenar = QtGui.QWidget()
        self.ordenar.setObjectName(_fromUtf8("ordenar"))
        self.gridLayout_5 = QtGui.QGridLayout(self.ordenar)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.ordenarPushButton = QtGui.QPushButton(self.ordenar)
        self.ordenarPushButton.setObjectName(_fromUtf8("ordenarPushButton"))
        self.gridLayout_5.addWidget(self.ordenarPushButton, 7, 0, 1, 1)
        self.distanciaRadioButton = QtGui.QRadioButton(self.ordenar)
        self.distanciaRadioButton.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.distanciaRadioButton.setObjectName(_fromUtf8("distanciaRadioButton"))
        self.gridLayout_5.addWidget(self.distanciaRadioButton, 4, 0, 1, 1)
        self.origenRadioButton = QtGui.QRadioButton(self.ordenar)
        self.origenRadioButton.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.origenRadioButton.setObjectName(_fromUtf8("origenRadioButton"))
        self.gridLayout_5.addWidget(self.origenRadioButton, 1, 0, 1, 1)
        self.salidaRadioButton = QtGui.QRadioButton(self.ordenar)
        self.salidaRadioButton.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.salidaRadioButton.setObjectName(_fromUtf8("salidaRadioButton"))
        self.gridLayout_5.addWidget(self.salidaRadioButton, 5, 0, 1, 1)
        self.arriboRadioButton = QtGui.QRadioButton(self.ordenar)
        self.arriboRadioButton.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.arriboRadioButton.setObjectName(_fromUtf8("arriboRadioButton"))
        self.gridLayout_5.addWidget(self.arriboRadioButton, 6, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.ordenar)
        self.label_8.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.destinoRadioButton = QtGui.QRadioButton(self.ordenar)
        self.destinoRadioButton.setStyleSheet(_fromUtf8("font: 25 10pt \"Bookman Old Style\";"))
        self.destinoRadioButton.setObjectName(_fromUtf8("destinoRadioButton"))
        self.gridLayout_5.addWidget(self.destinoRadioButton, 3, 0, 1, 1)
        self.gridTabWidget.addTab(self.ordenar, _fromUtf8(""))
        self.recorridos = QtGui.QWidget()
        self.recorridos.setObjectName(_fromUtf8("recorridos"))
        self.gridLayout_7 = QtGui.QGridLayout(self.recorridos)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.profundidadPushButton = QtGui.QPushButton(self.recorridos)
        self.profundidadPushButton.setObjectName(_fromUtf8("profundidadPushButton"))
        self.gridLayout_7.addWidget(self.profundidadPushButton, 2, 0, 1, 1)
        self.anchuraPushButton = QtGui.QPushButton(self.recorridos)
        self.anchuraPushButton.setObjectName(_fromUtf8("anchuraPushButton"))
        self.gridLayout_7.addWidget(self.anchuraPushButton, 2, 1, 1, 1)
        self.primPushButton = QtGui.QPushButton(self.recorridos)
        self.primPushButton.setObjectName(_fromUtf8("primPushButton"))
        self.gridLayout_7.addWidget(self.primPushButton, 3, 0, 1, 1)
        self.kruskalPushButton = QtGui.QPushButton(self.recorridos)
        self.kruskalPushButton.setObjectName(_fromUtf8("kruskalPushButton"))
        self.gridLayout_7.addWidget(self.kruskalPushButton, 3, 1, 1, 1)
        self.gridTabWidget.addTab(self.recorridos, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.gridTabWidget, 0, 1, 1, 1)
        formMainWindow.setCentralWidget(self.widget)
        self.statusbar = QtGui.QStatusBar(formMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        formMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(formMainWindow)
        self.gridTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(formMainWindow)

    def retranslateUi(self, formMainWindow):
        formMainWindow.setWindowTitle(_translate("formMainWindow", "Aerolinea", None))
        self.label_9.setText(_translate("formMainWindow", "Agregar nodos", None))
        self.agregarPushButton.setText(_translate("formMainWindow", "Agregar", None))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.agregar), _translate("formMainWindow", "Agregar", None))
        self.destino.setText(_translate("formMainWindow", "Ciudad destino", None))
        self.origen.setText(_translate("formMainWindow", "Ciudad origen", None))
        self.fechaArribo.setText(_translate("formMainWindow", "Fecha arribo", None))
        self.distancia.setText(_translate("formMainWindow", "Distancia", None))
        self.fechaSalida.setText(_translate("formMainWindow", "Fecha salida", None))
        self.registrarPushButton.setText(_translate("formMainWindow", "Registrar", None))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.conectar), _translate("formMainWindow", "Conectar", None))
        self.mostrarPushButton.setText(_translate("formMainWindow", "Mostrar", None))
        item = self.mostrarTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("formMainWindow", "Origen", None))
        item = self.mostrarTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("formMainWindow", "Destino", None))
        item = self.mostrarTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("formMainWindow", "Distancia", None))
        item = self.mostrarTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("formMainWindow", "Salida", None))
        item = self.mostrarTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("formMainWindow", "Arribo", None))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.mostrar), _translate("formMainWindow", "Mostrar", None))
        self.buscarPushButton.setText(_translate("formMainWindow", "Buscar", None))
        self.buscarLineEdit.setText(_translate("formMainWindow", "Busca origen", None))
        item = self.modificarTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("formMainWindow", "Origen", None))
        item = self.modificarTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("formMainWindow", "Destino", None))
        item = self.modificarTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("formMainWindow", "Distancia", None))
        item = self.modificarTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("formMainWindow", "Salida", None))
        item = self.modificarTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("formMainWindow", "Arribo", None))
        self.label_3.setText(_translate("formMainWindow", "Ciudad origen", None))
        self.label_4.setText(_translate("formMainWindow", "Ciudad destino", None))
        self.label_5.setText(_translate("formMainWindow", "Distancia", None))
        self.label.setText(_translate("formMainWindow", "Fecha salida", None))
        self.label_6.setText(_translate("formMainWindow", "Obligatorio", None))
        self.label_2.setText(_translate("formMainWindow", "Fecha arribo", None))
        self.label_7.setText(_translate("formMainWindow", "Obligatorio", None))
        self.modificarPushButton.setText(_translate("formMainWindow", "Modificar", None))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.modificar), _translate("formMainWindow", "Modificar", None))
        self.ordenarPushButton.setText(_translate("formMainWindow", "Ordenar", None))
        self.distanciaRadioButton.setText(_translate("formMainWindow", "Distancia", None))
        self.origenRadioButton.setText(_translate("formMainWindow", "Origen", None))
        self.salidaRadioButton.setText(_translate("formMainWindow", "Salida", None))
        self.arriboRadioButton.setText(_translate("formMainWindow", "Arribo", None))
        self.label_8.setText(_translate("formMainWindow", "Ordenar por:", None))
        self.destinoRadioButton.setText(_translate("formMainWindow", "Destino", None))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.ordenar), _translate("formMainWindow", "Ordenar", None))
        self.profundidadPushButton.setText(_translate("formMainWindow", "Profundidad", None))
        self.anchuraPushButton.setText(_translate("formMainWindow", "Anchura", None))
        self.primPushButton.setText(_translate("formMainWindow", "Prim", None))
        self.kruskalPushButton.setText(_translate("formMainWindow", "Kruskal", None))
        self.gridTabWidget.setTabText(self.gridTabWidget.indexOf(self.recorridos), _translate("formMainWindow", "Recorridos", None))

